### PR TITLE
Add Vue Style Guide

### PR DESCRIPTION
**Pull request by spaceninja**
Vue has it's own set of best practices separate from JS code conventions, and I think it'd be worth having a guide page. Even it for now, it just links to these external guides.

### CODE REVIEW

**Comment by gerardo-rodriguez** [comment]
Yep, I agree. Previous Vue.js projects began before the [Vue.js style guide](https://vuejs.org/v2/style-guide/) existed. I agree it's a good idea to follow their style guide. 😉

**Comment by Paul-Hebert** [comment]
Good call. Thanks for doing this @spaceninja !

**Comment by gerardo-rodriguez** [comment]
@spaceninja I haven't dug into it but how does the Deverus Vue.js Style Guide differ from the Vue.js Style Guide?

**Comment by gerardo-rodriguez** [comment]
> @spaceninja I haven't dug into it but how does the Deverus Vue.js Style Guide differ from the Vue.js Style Guide?

Watching the video now, FWIW. 😬

**Comment by spaceninja** [comment]
> how does the Deverus Vue.js Style Guide differ from the Vue.js Style Guide?

I'll be honest with you, I haven't fully investigated. I watched Erik's video about that guide, and the recommendations made sense for the most part. The TODO here is probably "read both guides and extract the parts we like from each".

That may be something I do as I work on this project, but for now I think just linking to each is a good starting point for anyone looking to write Vue.

**Pull request merged**
